"use client";

import { useEffect, useMemo, useState } from "react";
import IntelligenceGlobe, { type GlobeEvent } from "./IntelligenceGlobe";

export type CryptoSignal = "ACCUMULATE" | "HOLD" | "WATCH" | "AVOID";
export type CryptoAsset = { symbol:string; name:string; sector:string; price:number; change24h:number; change7d:number; volume24h:number; volatility:number; score:number; signal:CryptoSignal; allocationTactical:number; allocationCycle:number; rationale:string; risk:string; source?:string; sourceUrl?:string; observedAt?:string; exchangePrices?:Record<string,number>; spreadBps?:number; feedQuality?:string; futures?:{contract:string;markPrice:number;indexPrice:number;fundingRate:number;nextFundingTime:number;openInterest:number;observedAt:string;source:string} };
export type CryptoSector = { name:string; score:number; change:number };
export type CryptoDashboard = { updatedAt:string; dataMode:string; regime:string; score:number; stableReserve:number; btcDominance:number; feedQuality?:string; portfolioValue:number; dayChange:number; maxDrawdown:number; history:number[]; assets:CryptoAsset[]; sectors:CryptoSector[] };
type CryptoEvent = { id:string; timestamp:string; title:string; source:string; sourceUrl?:string; status:string; impact:string; companies:string[]; summary:string };

const KRAKEN:Record<string,string>={BTC:"XBTUSD",ETH:"ETHUSD",SOL:"SOLUSD",LINK:"LINKUSD",AVAX:"AVAXUSD",XRP:"XRPUSD",ADA:"ADAUSD",DOT:"DOTUSD",LTC:"LTCUSD",UNI:"UNIUSD"};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value<10?2:0}).format(value);
const volume=(value:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value);

function CryptoChart({values}:{values:number[]}){const w=720,h=170,min=Math.min(...values)*.998,max=Math.max(...values)*1.002,range=Math.max(1,max-min),pts=values.map((value,index)=>`${index/Math.max(1,values.length-1)*w},${h-(value-min)/range*h}`).join(" ");return <svg className="crypto-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="24-hour model crypto portfolio performance"><defs><linearGradient id="cryptoFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#76ffe2" stopOpacity=".32"/><stop offset="1" stopColor="#76ffe2" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(line=><line key={line} x1="0" x2={w} y1={line*h/3} y2={line*h/3} stroke="rgba(255,255,255,.07)"/>)}<polygon points={`0,${h} ${pts} ${w},${h}`} fill="url(#cryptoFill)"/><polyline points={pts} fill="none" stroke="#76ffe2" strokeWidth="3"/></svg>}

async function browserQuote(symbol:string){
  const [coinbase,kraken]=await Promise.allSettled([
    fetch(`https://api.exchange.coinbase.com/products/${symbol}-USD/stats`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()),
    fetch(`https://api.kraken.com/0/public/Ticker?pair=${KRAKEN[symbol]}`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()),
  ]);
  const prices:Record<string,number>={};let change24h:number|undefined;
  if(coinbase.status==="fulfilled"){prices.Coinbase=Number(coinbase.value.last);change24h=(prices.Coinbase/Number(coinbase.value.open)-1)*100;}
  if(kraken.status==="fulfilled"&&!kraken.value.error?.length){const row=Object.values(kraken.value.result)[0] as {c:string[];o:string};prices.Kraken=Number(row.c[0]);if(change24h===undefined)change24h=(prices.Kraken/Number(row.o)-1)*100;}
  const list=Object.values(prices).filter(Number.isFinite);if(!list.length)throw new Error("No browser feed");
  const price=list.reduce((a,b)=>a+b,0)/list.length,spreadBps=list.length>1?(Math.max(...list)-Math.min(...list))/price*10000:0;
  return {price,change24h:change24h??0,exchangePrices:prices,spreadBps,feedQuality:list.length>1&&spreadBps<=100?"VERIFIED":"SINGLE SOURCE"};
}

export default function CryptoSection({data,events=[]}:{data:CryptoDashboard;events?:CryptoEvent[]}){
  const [horizon,setHorizon]=useState<"tactical"|"cycle">("tactical"),[selected,setSelected]=useState(data.assets[0]?.symbol),[selectedOrbit,setSelectedOrbit]=useState<string>(),[report,setReport]=useState(false),[assets,setAssets]=useState(data.assets),[liveAt,setLiveAt]=useState(data.updatedAt),[feed,setFeed]=useState(data.feedQuality??"SCHEDULED SNAPSHOT");
  useEffect(()=>setAssets(data.assets),[data.assets]);
  useEffect(()=>{let active=true;const refresh=async()=>{const rows=await Promise.allSettled(data.assets.map(async asset=>({symbol:asset.symbol,...await browserQuote(asset.symbol)})));if(!active)return;let verified=0;setAssets(current=>current.map(asset=>{const row=rows.find(item=>item.status==="fulfilled"&&item.value.symbol===asset.symbol);if(!row||row.status!=="fulfilled")return asset;if(row.value.feedQuality==="VERIFIED")verified++;return {...asset,...row.value,observedAt:new Date().toISOString(),source:"Coinbase + Kraken browser cross-check"};}));if(rows.some(row=>row.status==="fulfilled")){setLiveAt(new Date().toISOString());setFeed(verified===data.assets.length?"LIVE · 2-EXCHANGE VERIFIED":"LIVE · PARTIAL CROSS-CHECK");}};refresh();const timer=window.setInterval(refresh,30_000);return()=>{active=false;window.clearInterval(timer)}},[data.assets]);
  const asset=useMemo(()=>assets.find(item=>item.symbol===selected)??assets[0],[assets,selected]),cryptoEvents=events.filter(event=>event.companies.some(symbol=>assets.some(asset=>asset.symbol===symbol))).slice(0,6),cryptoGlobeEvents:GlobeEvent[]=assets.map(item=>({id:`crypto-orbit-${item.symbol}`,region:"GLOBAL",title:`${item.name} ${item.change24h>=0?"+":""}${item.change24h.toFixed(2)}% · ${item.signal}`,status:item.feedQuality==="VERIFIED"?"CONFIRMED":"DEVELOPING",impact:item.change24h>.25?"POSITIVE":item.change24h<-.25?"NEGATIVE":"MIXED",companies:[item.symbol]}));
  if(!asset)return null;const allocation=(item:CryptoAsset)=>horizon==="tactical"?item.allocationTactical:item.allocationCycle;
  return <section className="crypto-zone" id="crypto">
    <div className="crypto-title"><div><p className="panel-kicker">24/7 DIGITAL-ASSET INTELLIGENCE · {assets.length} ELIGIBLE ASSETS</p><h2>Crypto command centre</h2><p>Established, multi-exchange assets only. Inclusion improves research coverage—it is not an automatic recommendation to buy every asset.</p></div><div className="crypto-clock"><i/>{feed}<small>{new Date(liveAt).toLocaleString("en-IN",{timeZone:"UTC"})} UTC · browser 30s / verified archive 10m</small></div></div>
    <div className="crypto-status-grid"><article><span>MARKET REGIME</span><strong>{data.regime}</strong></article><article><span>CRYPTO RISK SCORE</span><strong>{data.score}<small>/100</small></strong></article><article><span>STABLECOIN RESERVE</span><strong>{data.stableReserve}%</strong></article><article><span>BTC DOMINANCE</span><strong>{data.btcDominance}%</strong></article></div>
    <div className="crypto-full-grid"><article className="panel crypto-performance"><div className="panel-head"><div><p className="panel-kicker">CRYPTO PORTFOLIO VALUE / MODEL</p><h2>{money(data.portfolioValue)}</h2></div><span className="live-badge">● 24/7 UTC</span></div><div className="portfolio-meta"><span className={data.dayChange>=0?"positive":"negative"}>{data.dayChange>=0?"+":""}{data.dayChange}% 24H</span><span><b>{data.maxDrawdown}%</b> max drawdown</span><span><b>{data.stableReserve}%</b> reserve</span></div><CryptoChart values={data.history}/><div className="chart-labels"><span>-24H</span><span>-18H</span><span>-12H</span><span>-6H</span><span>NOW</span></div></article>
      <article className="panel crypto-feed"><p className="panel-kicker">PRICE VERIFICATION MATRIX</p><h3>{asset.symbol} cross-exchange check</h3><div className={`feed-verdict ${(asset.feedQuality??feed).toLowerCase().replaceAll(" ","-")}`}><i/>{asset.feedQuality??feed}</div><dl>{Object.entries(asset.exchangePrices??{}).map(([exchange,price])=><div key={exchange}><dt>{exchange}</dt><dd>{money(price)}</dd></div>)}<div><dt>CONSENSUS</dt><dd>{money(asset.price)}</dd></div><div><dt>EXCHANGE SPREAD</dt><dd>{(asset.spreadBps??0).toFixed(1)} bps</dd></div></dl><small>Prices are averaged only when exchange divergence remains inside the 1% anomaly limit.</small></article>
      <article className="panel crypto-orbit"><div className="panel-head"><div><p className="panel-kicker">DIGITAL-ASSET SIGNAL ORBIT</p><h3>Drag, zoom and click a coin to inspect its 24/7 signal</h3></div><span className="live-badge">● LIVE ORBIT</span></div><IntelligenceGlobe mode="crypto" events={cryptoGlobeEvents} selectedId={selectedOrbit} onSelect={event=>{setSelectedOrbit(event.id);setSelected(event.companies[0])}}/>{selectedOrbit&&<button className="crypto-orbit-card" onClick={()=>setReport(true)}><span>{asset.symbol} · {asset.feedQuality??feed}</span><strong>{asset.name} {asset.change24h>=0?"+":""}{asset.change24h.toFixed(2)}%</strong><small>{asset.signal} · {asset.score}/100 · OPEN FULL EVIDENCE →</small></button>}<div className="impact-legend"><span><i className="positive-dot"/>POSITIVE</span><span><i className="mixed-dot"/>MIXED</span><span><i className="negative-dot"/>NEGATIVE</span></div></article>
    </div>
    <div className="crypto-grid"><article className="panel crypto-assets"><div className="panel-head"><div><p className="panel-kicker">DECISION ENGINE</p><h3>Highest-conviction crypto signals</h3></div><div className="horizon-toggle"><button className={horizon==="tactical"?"active":""} onClick={()=>setHorizon("tactical")}>TACTICAL 24H</button><button className={horizon==="cycle"?"active":""} onClick={()=>setHorizon("cycle")}>CYCLE 90D</button></div></div><div className="crypto-table"><div className="crypto-row crypto-head"><span>ASSET</span><span>PRICE / 24H</span><span>RISK</span><span>SIGNAL</span><span>ALLOCATION</span></div>{assets.map(item=><button key={item.symbol} className={`crypto-row ${selected===item.symbol?"selected":""}`} onClick={()=>setSelected(item.symbol)}><span><b>{item.symbol}</b><small>{item.name} · {item.sector}</small></span><span><b>{money(item.price)}</b><small className={item.change24h>=0?"positive":"negative"}>{item.change24h>=0?"+":""}{item.change24h.toFixed(2)}%</small></span><span><b>{item.volatility}%</b><small>24H range</small></span><span><em className={`signal ${item.signal.toLowerCase()}`}>{item.signal}</em><small>{item.score}/100</small></span><span className="crypto-allocation"><b>{allocation(item)}%</b><i><u style={{width:`${allocation(item)*4}%`}}/></i></span></button>)}</div></article>
      <aside className="panel crypto-thesis"><p className="panel-kicker">SELECTED DIGITAL ASSET</p><div className="crypto-symbol"><div><h2>{asset.symbol}</h2><span>{asset.name}</span></div><div className="score-ring" style={{"--score":asset.score} as React.CSSProperties}><strong>{asset.score}</strong><small>24/7<br/>SCORE</small></div></div><div className="thesis-block"><p>WHY NOW · MODEL INFERENCE</p><span>{asset.rationale}</span></div><div className="thesis-block risk"><p>HARD INVALIDATION</p><span>{asset.risk}</span></div><dl className="crypto-metrics"><div><dt>24H VOLUME</dt><dd>{volume(asset.volume24h)} {asset.symbol}</dd></div><div><dt>7D MOVE</dt><dd className={asset.change7d>=0?"positive":"negative"}>{asset.change7d>=0?"+":""}{asset.change7d}%</dd></div><div><dt>TRADE LAB</dt><dd>SPOT + FUTURES</dd></div><div><dt>ACTION</dt><dd>ENTRY / EXIT LEVELS</dd></div></dl><a className="review-button" href="#trading">OPEN BUY / SELL LEVELS <span>→</span></a><button className="review-button" onClick={()=>setReport(true)}>OPEN FULL CRYPTO EVIDENCE <span>→</span></button></aside>
      <article className="panel crypto-portfolio"><div className="panel-head"><div><p className="panel-kicker">RISK-BUDGETED PORTFOLIO</p><h3>{horizon==="tactical"?"Tactical 24-hour model":"90-day cycle model"}</h3></div><span className="muted">SPOT · NO AUTO-TRADE</span></div><div className="crypto-rings">{assets.map(item=><div key={item.symbol}><span>{item.symbol}</span><i><u style={{width:`${allocation(item)}%`}}/></i><b>{allocation(item)}%</b></div>)}<div className="reserve"><span>USDC RESERVE</span><i><u style={{width:`${data.stableReserve}%`}}/></i><b>{data.stableReserve}%</b></div></div><p>Allocation is volatility-sized. Crypto risk is isolated from the NSE portfolio.</p></article>
      <article className="panel crypto-sectors"><div className="panel-head"><div><p className="panel-kicker">CRYPTO ROTATION</p><h3>Sector relative strength</h3></div><span className="muted">24/7 MODEL</span></div>{data.sectors.map(sector=><div className="sector-row" key={sector.name}><span>{sector.name}</span><i><u style={{width:`${sector.score}%`}}/></i><strong>{sector.score}</strong><em className={sector.change>=0?"positive":"negative"}>{sector.change>=0?"+":""}{sector.change}%</em></div>)}</article>
      <article className="panel crypto-news"><div className="panel-head"><div><p className="panel-kicker">CRYPTO EVIDENCE INTELLIGENCE</p><h3>Cross-checked events mapped to digital assets</h3></div><span className="muted">SOURCE FIRST</span></div>{cryptoEvents.length?cryptoEvents.map(event=><article key={event.id}><span className={`status-dot ${event.status.toLowerCase()}`}/><div><small>{event.status} · {event.impact}</small><h4>{event.title}</h4><p>{event.summary}</p>{event.sourceUrl?<a href={event.sourceUrl} target="_blank" rel="noreferrer">OPEN ORIGINAL SOURCE ↗</a>:<em>SOURCE REQUIRED</em>}</div></article>):<div className="crypto-empty"><strong>No verified crypto event in the current cycle.</strong><p>The engine will not fabricate a catalyst. Scheduled research is scanning for Bitcoin, Ethereum, Solana, regulation, ETFs, exchanges and security events.</p></div>}</article>
    </div><p className="crypto-data-note">{data.dataMode}. Direct spot prices refresh every 30 seconds; GitHub stores a Coinbase + Kraken verified snapshot every 10 minutes. The Trade Lab converts the latest reference into conditional entry, exit, stop and target levels for spot and supported perpetual futures.</p>
    {report&&<div className="report-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setReport(false)}><aside className="report-drawer crypto-report" role="dialog" aria-modal="true"><button className="report-close" onClick={()=>setReport(false)}>CLOSE ×</button><p className="panel-kicker">FULL CRYPTO EVIDENCE / {asset.sector}</p><h2>{asset.symbol} <small>{asset.name}</small></h2><div className="report-verdict"><em className={`signal ${asset.signal.toLowerCase()}`}>{asset.signal}</em><strong>{asset.score}/100</strong><span>{asset.feedQuality??feed}</span></div><section><h3>Decision thesis</h3><p>{asset.rationale}</p><p className="risk-copy"><b>INVALIDATION:</b> {asset.risk}</p></section><section><h3>Cross-exchange market record</h3><dl className="report-grid"><div><dt>Consensus spot</dt><dd>{money(asset.price)}</dd></div><div><dt>24H move</dt><dd>{asset.change24h.toFixed(2)}%</dd></div><div><dt>Exchange spread</dt><dd>{(asset.spreadBps??0).toFixed(1)} bps</dd></div><div><dt>24H range</dt><dd>{asset.volatility}%</dd></div><div><dt>Observed UTC</dt><dd>{asset.observedAt?new Date(asset.observedAt).toLocaleString("en-IN",{timeZone:"UTC"}):"Awaiting verified cycle"}</dd></div><div><dt>Data source</dt><dd>{asset.source??"Awaiting live feed"}</dd></div></dl>{asset.sourceUrl&&<a className="report-primary-link" href={asset.sourceUrl} target="_blank" rel="noreferrer">OPEN SOURCE MARKET PAGE ↗</a>}</section><section><h3>Portfolio action</h3><dl className="report-grid"><div><dt>Tactical allocation</dt><dd>{asset.allocationTactical}%</dd></div><div><dt>Cycle allocation</dt><dd>{asset.allocationCycle}%</dd></div><div><dt>Trade Lab</dt><dd>SPOT + FUTURES</dd></div><div><dt>Action</dt><dd>ENTRY / EXIT LEVELS</dd></div></dl><a className="report-primary-link" href="#trading" onClick={()=>setReport(false)}>OPEN BUY / SELL LEVELS →</a></section><section><h3>Evidence boundaries</h3><p>Public futures telemetry is used only for market context. Exchange flows, liquidation clusters and whale concentration remain excluded until verified providers are connected.</p></section></aside></div>}
  </section>;
}
