"use client";

import { useMemo, useState } from "react";

export type CryptoSignal = "ACCUMULATE" | "HOLD" | "WATCH" | "AVOID";
export type CryptoAsset = { symbol:string; name:string; sector:string; price:number; change24h:number; change7d:number; volume24h:number; volatility:number; score:number; signal:CryptoSignal; allocationTactical:number; allocationCycle:number; rationale:string; risk:string; source?:string; sourceUrl?:string; observedAt?:string };
export type CryptoSector = { name:string; score:number; change:number };
export type CryptoDashboard = { updatedAt:string; dataMode:string; regime:string; score:number; stableReserve:number; btcDominance:number; assets:CryptoAsset[]; sectors:CryptoSector[] };

const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value<10?2:0}).format(value);
const volume=(value:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value);

export default function CryptoSection({data}:{data:CryptoDashboard}){
  const [horizon,setHorizon]=useState<"tactical"|"cycle">("tactical");
  const [selected,setSelected]=useState(data.assets[0]?.symbol);
  const [report,setReport]=useState(false);
  const asset=useMemo(()=>data.assets.find(item=>item.symbol===selected)??data.assets[0],[data.assets,selected]);
  if(!asset)return null;
  const allocation=(item:CryptoAsset)=>horizon==="tactical"?item.allocationTactical:item.allocationCycle;
  return <section className="crypto-zone" id="crypto">
    <div className="crypto-title"><div><p className="panel-kicker">24/7 DIGITAL-ASSET INTELLIGENCE</p><h2>Crypto command centre</h2><p>Continuous UTC evidence, liquidity and volatility analysis. Crypto risk stays separate from the equity portfolio.</p></div><div className="crypto-clock"><i/>SCANNING EVERY 10 MIN<small>{new Date(data.updatedAt).toLocaleString("en-IN",{timeZone:"UTC"})} UTC</small></div></div>
    <div className="crypto-status-grid"><article><span>MARKET REGIME</span><strong>{data.regime}</strong></article><article><span>CRYPTO RISK SCORE</span><strong>{data.score}<small>/100</small></strong></article><article><span>STABLECOIN RESERVE</span><strong>{data.stableReserve}%</strong></article><article><span>BTC DOMINANCE</span><strong>{data.btcDominance}%</strong></article></div>
    <div className="crypto-grid"><article className="panel crypto-assets"><div className="panel-head"><div><p className="panel-kicker">SPOT PORTFOLIO ENGINE</p><h3>24/7 allocation signals</h3></div><div className="horizon-toggle"><button className={horizon==="tactical"?"active":""} onClick={()=>setHorizon("tactical")}>TACTICAL 24H</button><button className={horizon==="cycle"?"active":""} onClick={()=>setHorizon("cycle")}>CYCLE 90D</button></div></div>
      <div className="crypto-table"><div className="crypto-row crypto-head"><span>ASSET</span><span>PRICE / 24H</span><span>RISK</span><span>SIGNAL</span><span>ALLOCATION</span></div>{data.assets.map(item=><button key={item.symbol} className={`crypto-row ${selected===item.symbol?"selected":""}`} onClick={()=>setSelected(item.symbol)}><span><b>{item.symbol}</b><small>{item.name} · {item.sector}</small></span><span><b>{money(item.price)}</b><small className={item.change24h>=0?"positive":"negative"}>{item.change24h>=0?"+":""}{item.change24h}%</small></span><span><b>{item.volatility}%</b><small>24H range</small></span><span><em className={`signal ${item.signal.toLowerCase()}`}>{item.signal}</em><small>{item.score}/100</small></span><span className="crypto-allocation"><b>{allocation(item)}%</b><i><u style={{width:`${allocation(item)*4}%`}}/></i></span></button>)}</div>
    </article><aside className="panel crypto-thesis"><p className="panel-kicker">SELECTED DIGITAL ASSET</p><div className="crypto-symbol"><div><h2>{asset.symbol}</h2><span>{asset.name}</span></div><div className="score-ring" style={{"--score":asset.score} as React.CSSProperties}><strong>{asset.score}</strong><small>24/7<br/>SCORE</small></div></div><div className="thesis-block"><p>WHY NOW · MODEL INFERENCE</p><span>{asset.rationale}</span></div><div className="thesis-block risk"><p>HARD INVALIDATION</p><span>{asset.risk}</span></div><dl className="crypto-metrics"><div><dt>24H VOLUME</dt><dd>{volume(asset.volume24h)} {asset.symbol}</dd></div><div><dt>7D MOVE</dt><dd className={asset.change7d>=0?"positive":"negative"}>{asset.change7d>=0?"+":""}{asset.change7d}%</dd></div><div><dt>EXECUTION</dt><dd>SPOT ONLY</dd></div><div><dt>LEVERAGE</dt><dd>DISABLED</dd></div></dl><button className="review-button" onClick={()=>setReport(true)}>OPEN CRYPTO EVIDENCE <span>→</span></button></aside>
      <article className="panel crypto-portfolio"><div className="panel-head"><div><p className="panel-kicker">RISK-BUDGETED PORTFOLIO</p><h3>{horizon==="tactical"?"Tactical 24-hour model":"90-day cycle model"}</h3></div><span className="muted">SPOT · NO AUTO-TRADE</span></div><div className="crypto-rings">{data.assets.map(item=><div key={item.symbol}><span>{item.symbol}</span><i><u style={{width:`${allocation(item)}%`}}/></i><b>{allocation(item)}%</b></div>)}<div className="reserve"><span>USDC RESERVE</span><i><u style={{width:`${data.stableReserve}%`}}/></i><b>{data.stableReserve}%</b></div></div><p>Allocation is volatility-sized. A rebalance is proposed only when score, liquidity and drawdown rules agree.</p></article>
      <article className="panel crypto-sectors"><div className="panel-head"><div><p className="panel-kicker">CRYPTO ROTATION</p><h3>Sector relative strength</h3></div><span className="muted">24/7 MODEL</span></div>{data.sectors.map(sector=><div className="sector-row" key={sector.name}><span>{sector.name}</span><i><u style={{width:`${sector.score}%`}}/></i><strong>{sector.score}</strong><em className={sector.change>=0?"positive":"negative"}>{sector.change>=0?"+":""}{sector.change}%</em></div>)}</article>
    </div><p className="crypto-data-note">{data.dataMode}. Funding, open interest, liquidations, on-chain flows and whale concentration remain marked unavailable until verified providers are connected.</p>
    {report&&<div className="report-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setReport(false)}><aside className="report-drawer crypto-report" role="dialog" aria-modal="true"><button className="report-close" onClick={()=>setReport(false)}>CLOSE ×</button><p className="panel-kicker">FULL CRYPTO EVIDENCE / {asset.sector}</p><h2>{asset.symbol} <small>{asset.name}</small></h2><div className="report-verdict"><em className={`signal ${asset.signal.toLowerCase()}`}>{asset.signal}</em><strong>{asset.score}/100</strong><span>24/7 UTC model</span></div><section><h3>Decision thesis</h3><p>{asset.rationale}</p><p className="risk-copy"><b>INVALIDATION:</b> {asset.risk}</p></section><section><h3>Continuous market record</h3><dl className="report-grid"><div><dt>Spot price</dt><dd>{money(asset.price)}</dd></div><div><dt>24H move</dt><dd>{asset.change24h}%</dd></div><div><dt>24H volume</dt><dd>{volume(asset.volume24h)} {asset.symbol}</dd></div><div><dt>24H range</dt><dd>{asset.volatility}%</dd></div><div><dt>Observed UTC</dt><dd>{asset.observedAt?new Date(asset.observedAt).toLocaleString("en-IN",{timeZone:"UTC"}):"Awaiting live cycle"}</dd></div><div><dt>Data source</dt><dd>{asset.source??"Demonstration seed"}</dd></div></dl>{asset.sourceUrl&&<a className="report-primary-link" href={asset.sourceUrl} target="_blank" rel="noreferrer">OPEN SOURCE MARKET PAGE ↗</a>}</section><section><h3>Derivatives and on-chain checks</h3><dl className="report-grid"><div><dt>Funding / OI</dt><dd>PROVIDER REQUIRED</dd></div><div><dt>Liquidations</dt><dd>PROVIDER REQUIRED</dd></div><div><dt>Exchange flows</dt><dd>PROVIDER REQUIRED</dd></div><div><dt>Whale concentration</dt><dd>PROVIDER REQUIRED</dd></div></dl></section><section><h3>Execution guardrails</h3><p>Spot only. No leverage and no automatic order execution. Crypto allocation is isolated from the equity risk budget; review after each 10-minute scan and on drawdown alerts.</p></section></aside></div>}
  </section>;
}
