"use client";

import { useEffect, useMemo, useState } from "react";

type Stock = { symbol:string; company:string; price:number; change:number; score:number; signal:string };
type Coin = { symbol:string; name:string; price:number; change24h:number; score:number; signal:string; futures?:FuturesQuote & {contract?:string;source?:string} };
type Market = "NSE" | "CRYPTO";
type Product = "SPOT" | "FUTURES";
type Side = "BUY" | "SELL";
type OrderType = "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT";
type MarginMode = "ISOLATED" | "CROSS";
type FuturesQuote = { markPrice:number; indexPrice:number; fundingRate:number; nextFundingTime:number; openInterest:number; observedAt:string };
type PaperOrder = {
  id:string; createdAt:string; market:Market; product:Product; symbol:string; side:Side; orderType:OrderType;
  quantity:number; entry:number; stop:number; target:number; leverage:number; marginMode:MarginMode; reduceOnly:boolean;
  notional:number; margin:number; risk:number; status:"OPEN"|"CLOSED"|"CANCELLED";
};

const STORAGE_KEY="wmi-paper-orders-v2";
const WATCH_KEY="wmi-trade-watchlist-v1";
const usd=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value<10?3:2}).format(value||0);
const inr=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value||0);
const compact=(value:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:2}).format(value||0);
const number=(value:string,fallback=0)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback};

async function getFuturesQuote(symbol:string):Promise<FuturesQuote>{
  const contract=`${symbol}USDT`;
  const [premium,interest]=await Promise.all([
    fetch(`https://fapi.binance.com/fapi/v1/premiumIndex?symbol=${contract}`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject(new Error("mark feed unavailable"))),
    fetch(`https://fapi.binance.com/fapi/v1/openInterest?symbol=${contract}`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject(new Error("open-interest feed unavailable"))),
  ]);
  return {markPrice:Number(premium.markPrice),indexPrice:Number(premium.indexPrice),fundingRate:Number(premium.lastFundingRate)*100,nextFundingTime:Number(premium.nextFundingTime),openInterest:Number(interest.openInterest),observedAt:new Date().toISOString()};
}

export default function TradingDesk({stocks,coins}:{stocks:Stock[];coins:Coin[]}){
  const [market,setMarket]=useState<Market>("NSE"),[product,setProduct]=useState<Product>("SPOT"),[symbol,setSymbol]=useState(stocks[0]?.symbol??"HDFCBANK"),[side,setSide]=useState<Side>("BUY"),[orderType,setOrderType]=useState<OrderType>("LIMIT");
  const [quantity,setQuantity]=useState("1"),[entry,setEntry]=useState(String(stocks[0]?.price??0)),[stop,setStop]=useState(""),[target,setTarget]=useState(""),[account,setAccount]=useState("500000"),[riskPct,setRiskPct]=useState("1"),[leverage,setLeverage]=useState(2),[marginMode,setMarginMode]=useState<MarginMode>("ISOLATED"),[reduceOnly,setReduceOnly]=useState(false);
  const [orders,setOrders]=useState<PaperOrder[]>([]),[watchlist,setWatchlist]=useState<string[]>([]),[quote,setQuote]=useState<FuturesQuote>(),[quoteState,setQuoteState]=useState("PUBLIC FEED STANDBY"),[confirm,setConfirm]=useState<PaperOrder>(),[tab,setTab]=useState<"TICKET"|"POSITIONS"|"WATCHLIST">("TICKET");
  useEffect(()=>{try{setOrders(JSON.parse(localStorage.getItem(STORAGE_KEY)??"[]"));setWatchlist(JSON.parse(localStorage.getItem(WATCH_KEY)??"[]"))}catch{}},[]);
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(orders)),[orders]);
  useEffect(()=>localStorage.setItem(WATCH_KEY,JSON.stringify(watchlist)),[watchlist]);

  const instruments=market==="NSE"?stocks:coins;
  const instrument=useMemo(()=>instruments.find(item=>item.symbol===symbol)??instruments[0],[instruments,symbol]);
  const spotPrice=instrument?.price??0;
  useEffect(()=>{
    const next=(market==="NSE"?stocks:coins)[0];if(!next)return;
    setSymbol(next.symbol);setEntry(String(next.price));setStop("");setTarget("");setQuote(undefined);
  },[market,stocks,coins]);
  useEffect(()=>{if(instrument&&orderType==="MARKET")setEntry(String(quote?.markPrice||spotPrice))},[instrument,orderType,quote?.markPrice,spotPrice]);
  useEffect(()=>{
    if(!(market==="CRYPTO"&&product==="FUTURES")){setQuote(undefined);setQuoteState(product==="FUTURES"?"NSE LICENSED FEED REQUIRED":"SPOT CONSENSUS READY");return}
    const archived=coins.find(coin=>coin.symbol===symbol)?.futures;if(archived){setQuote(archived);setQuoteState("10-MINUTE VERIFIED FUTURES ARCHIVE")}
    let active=true;const refresh=()=>{setQuoteState("SYNCING PUBLIC FUTURES FEED");getFuturesQuote(symbol).then(value=>{if(active){setQuote(value);setQuoteState("LIVE PUBLIC FUTURES METRICS");if(orderType==="MARKET")setEntry(String(value.markPrice))}}).catch(()=>active&&setQuoteState(archived?"ARCHIVED FUTURES SNAPSHOT · LIVE RETRYING":"PUBLIC FEED UNAVAILABLE · SNAPSHOT FALLBACK"))};
    refresh();const timer=window.setInterval(refresh,30_000);return()=>{active=false;window.clearInterval(timer)};
  },[market,product,symbol,orderType]);

  const values=useMemo(()=>{const e=number(entry,spotPrice),s=number(stop),t=number(target),qty=number(quantity),capital=number(account),riskBudget=capital*number(riskPct)/100,unitRisk=Math.abs(e-s),suggested=unitRisk>0?riskBudget/unitRisk:0,notional=e*qty,margin=product==="FUTURES"?notional/leverage:notional,risk=unitRisk*qty,reward=Math.abs(t-e)*qty,rr=risk>0?reward/risk:0;
    const maintenance=.005,liq=product==="FUTURES"?(side==="BUY"?e*(1-1/leverage+maintenance):e*(1+1/leverage-maintenance)):0;
    return {e,s,t,qty,capital,riskBudget,unitRisk,suggested,notional,margin,risk,reward,rr,liq};},[entry,stop,target,quantity,account,riskPct,product,leverage,side,spotPrice]);
  const errors=useMemo(()=>{const rows:string[]=[];if(values.qty<=0)rows.push("Quantity must be greater than zero.");if(values.e<=0)rows.push("Entry price is required.");if(values.s<=0)rows.push("A protective stop is required.");if(values.t<=0)rows.push("A take-profit target is required.");if(side==="BUY"&&values.s>=values.e)rows.push("Long stop must be below entry.");if(side==="BUY"&&values.t<=values.e)rows.push("Long target must be above entry.");if(side==="SELL"&&values.s<=values.e)rows.push("Short stop must be above entry.");if(side==="SELL"&&values.t>=values.e)rows.push("Short target must be below entry.");if(values.margin>values.capital)rows.push("Required capital exceeds paper account.");return rows},[values,side]);
  const warnings=useMemo(()=>{const rows:string[]=[];if(number(riskPct)>2)rows.push("Risk budget is above the 2% guardrail.");if(product==="FUTURES"&&leverage>5)rows.push("Leverage above 5× materially increases liquidation risk.");if(values.rr>0&&values.rr<1.5)rows.push("Reward/risk is below 1.5×.");if(product==="FUTURES"&&market==="NSE")rows.push("Lot size, expiry and margin must be validated with an NSE-authorised broker before execution.");return rows},[riskPct,product,leverage,values.rr,market]);
  const addPaperOrder=()=>{if(errors.length)return;const order:PaperOrder={id:`P-${Date.now().toString(36).toUpperCase()}`,createdAt:new Date().toISOString(),market,product,symbol,side,orderType,quantity:values.qty,entry:values.e,stop:values.s,target:values.t,leverage:product==="FUTURES"?leverage:1,marginMode,reduceOnly,notional:values.notional,margin:values.margin,risk:values.risk,status:"OPEN"};setOrders(current=>[order,...current]);setConfirm(order);setTab("POSITIONS")};
  const updateStatus=(id:string,status:PaperOrder["status"])=>setOrders(current=>current.map(order=>order.id===id?{...order,status}:order));
  const selectMarket=(next:Market)=>{setMarket(next);setProduct("SPOT");setTab("TICKET")};
  const addWatch=()=>setWatchlist(current=>current.includes(`${market}:${symbol}`)?current:current.concat(`${market}:${symbol}`));
  return <section className="trade-lab" id="trading">
    <div className="trade-hero"><div><p className="panel-kicker">MULTI-ASSET TRADE LAB / PAPER MODE</p><h2>Spot + futures decision terminal</h2><p>Plan entries, size risk, monitor derivatives telemetry and rehearse execution without exposing exchange or broker credentials.</p></div><div className="execution-lock"><i/>LIVE EXECUTION LOCKED<small>Secure backend adapter required</small></div></div>
    <div className="trade-switchboard"><div className="segmented"><button className={market==="NSE"?"active":""} onClick={()=>selectMarket("NSE")}>NSE INDIA</button><button className={market==="CRYPTO"?"active":""} onClick={()=>selectMarket("CRYPTO")}>CRYPTO 24/7</button></div><div className="segmented"><button className={product==="SPOT"?"active":""} onClick={()=>setProduct("SPOT")}>SPOT</button><button className={product==="FUTURES"?"active":""} onClick={()=>setProduct("FUTURES")}>FUTURES</button></div><div className="trade-tabs"><button className={tab==="TICKET"?"active":""} onClick={()=>setTab("TICKET")}>ORDER TICKET</button><button className={tab==="POSITIONS"?"active":""} onClick={()=>setTab("POSITIONS")}>PAPER BOOK <b>{orders.filter(order=>order.status==="OPEN").length}</b></button><button className={tab==="WATCHLIST"?"active":""} onClick={()=>setTab("WATCHLIST")}>WATCHLIST <b>{watchlist.length}</b></button></div></div>
    {tab==="TICKET"&&<div className="trade-grid"><article className="panel order-ticket"><div className="ticket-head"><div><span>{market} / {product}</span><h3>{symbol}</h3><small>{"company" in (instrument??{})?instrument.company:instrument?.name} · {instrument?.signal} · score {instrument?.score}/100</small></div><div><strong>{market==="NSE"?inr(spotPrice):usd(spotPrice)}</strong><small className={("change" in (instrument??{})?instrument?.change:instrument?.change24h)>=0?"positive":"negative"}>{(("change" in (instrument??{})?instrument?.change:instrument?.change24h)??0).toFixed(2)}%</small></div></div>
      <div className="ticket-controls"><label>INSTRUMENT<select value={symbol} onChange={event=>{const next=event.target.value;setSymbol(next);const row=instruments.find(item=>item.symbol===next);if(row)setEntry(String(row.price));setQuote(undefined)}}>{instruments.map(item=><option key={item.symbol} value={item.symbol}>{item.symbol} · {"company" in item?item.company:item.name}</option>)}</select></label><label>ORDER TYPE<select value={orderType} onChange={event=>setOrderType(event.target.value as OrderType)}><option value="MARKET">Market</option><option value="LIMIT">Limit</option><option value="STOP">Stop market</option><option value="STOP_LIMIT">Stop limit</option></select></label></div>
      <div className="side-switch"><button className={side==="BUY"?"buy active":"buy"} onClick={()=>setSide("BUY")}>{product==="FUTURES"?"LONG":"BUY"}</button><button className={side==="SELL"?"sell active":"sell"} onClick={()=>setSide("SELL")}>{product==="FUTURES"?"SHORT":"SELL"}</button></div>
      <div className="ticket-fields"><label>QUANTITY<input inputMode="decimal" value={quantity} onChange={event=>setQuantity(event.target.value)}/><small>{market==="NSE"&&product==="FUTURES"?"Enter broker-verified lot quantity":"Units"}</small></label><label>ENTRY PRICE<input inputMode="decimal" value={entry} disabled={orderType==="MARKET"} onChange={event=>setEntry(event.target.value)}/><small>{orderType==="MARKET"?"Uses latest available price":"Planned trigger"}</small></label><label>STOP LOSS<input inputMode="decimal" value={stop} onChange={event=>setStop(event.target.value)} placeholder="Required"/><small>Hard risk limit</small></label><label>TAKE PROFIT<input inputMode="decimal" value={target} onChange={event=>setTarget(event.target.value)} placeholder="Required"/><small>Exit objective</small></label></div>
      {product==="FUTURES"&&<div className="futures-controls"><label>LEVERAGE <b>{leverage}×</b><input type="range" min="1" max={market==="NSE"?10:20} value={leverage} onChange={event=>setLeverage(Number(event.target.value))}/></label><label>MARGIN MODE<select value={marginMode} onChange={event=>setMarginMode(event.target.value as MarginMode)}><option value="ISOLATED">Isolated</option><option value="CROSS">Cross</option></select></label><label className="check-field"><input type="checkbox" checked={reduceOnly} onChange={event=>setReduceOnly(event.target.checked)}/> REDUCE ONLY</label><div className="contract-note"><b>{market==="CRYPTO"?`${symbol}USDT PERPETUAL`:`${symbol} MONTHLY FUTURE`}</b><span>{market==="CRYPTO"?"24/7 · 8-hour funding cycle":"NSE session · exchange expiry calendar"}</span></div></div>}
      <div className="ticket-actions"><button onClick={addWatch}>☆ ADD WATCH</button><button className="paper-submit" disabled={errors.length>0} onClick={addPaperOrder}>ADD TO PAPER PORTFOLIO →</button></div>{errors.length>0&&<div className="trade-messages error">{errors.map(error=><p key={error}>× {error}</p>)}</div>}{warnings.length>0&&<div className="trade-messages warn">{warnings.map(warning=><p key={warning}>△ {warning}</p>)}</div>}</article>
      <aside className="trade-side"><article className="panel risk-console"><p className="panel-kicker">RISK ENGINE</p><h3>Position sizing</h3><div className="risk-inputs"><label>PAPER ACCOUNT<input value={account} inputMode="decimal" onChange={event=>setAccount(event.target.value)}/></label><label>RISK / TRADE<input value={riskPct} inputMode="decimal" onChange={event=>setRiskPct(event.target.value)}/><span>%</span></label></div><dl><div><dt>Risk budget</dt><dd>{market==="NSE"?inr(values.riskBudget):usd(values.riskBudget)}</dd></div><div><dt>Suggested quantity</dt><dd>{values.suggested.toFixed(market==="CRYPTO"?4:0)}</dd></div><div><dt>Order notional</dt><dd>{market==="NSE"?inr(values.notional):usd(values.notional)}</dd></div><div><dt>{product==="FUTURES"?"Estimated margin":"Cash required"}</dt><dd>{market==="NSE"?inr(values.margin):usd(values.margin)}</dd></div><div><dt>Defined loss</dt><dd className="negative">{market==="NSE"?inr(values.risk):usd(values.risk)}</dd></div><div><dt>Reward / risk</dt><dd className={values.rr>=1.5?"positive":"negative"}>{values.rr.toFixed(2)}×</dd></div>{product==="FUTURES"&&<div><dt>Model liquidation</dt><dd>{market==="NSE"?inr(values.liq):usd(values.liq)}</dd></div>}</dl><small>Liquidation is a simplified estimate. Venue maintenance margin, fees and slippage can move the actual level.</small></article>
      <article className="panel telemetry"><div className="telemetry-head"><div><p className="panel-kicker">DERIVATIVES TELEMETRY</p><h3>{quoteState}</h3></div><i className={quote?"online":""}/></div>{market==="CRYPTO"&&product==="FUTURES"&&quote?<dl><div><dt>Mark price</dt><dd>{usd(quote.markPrice)}</dd></div><div><dt>Index price</dt><dd>{usd(quote.indexPrice)}</dd></div><div><dt>Basis</dt><dd>{((quote.markPrice/quote.indexPrice-1)*100).toFixed(3)}%</dd></div><div><dt>Funding / 8H</dt><dd className={quote.fundingRate>=0?"positive":"negative"}>{quote.fundingRate.toFixed(4)}%</dd></div><div><dt>Open interest</dt><dd>{compact(quote.openInterest)} {symbol}</dd></div><div><dt>Next funding</dt><dd>{new Date(quote.nextFundingTime).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</dd></div></dl>:<div className="telemetry-empty"><strong>{product==="SPOT"?"Futures metrics activate when FUTURES is selected.":"Provider adapter ready."}</strong><p>{market==="NSE"?"A licensed NSE/broker feed is required for live contract, lot, margin and open-interest data.":"Public mark, index, funding and open-interest data refresh every 30 seconds."}</p></div>}</article></aside></div>}
    {tab==="POSITIONS"&&<article className="panel paper-book"><div className="paper-head"><div><p className="panel-kicker">DEVICE-LOCAL PAPER LEDGER</p><h3>Orders and positions</h3></div><button onClick={()=>setOrders([])} disabled={!orders.length}>CLEAR CLOSED / RESET</button></div>{orders.length?<div className="paper-table"><div className="paper-row paper-labels"><span>ID / TIME</span><span>MARKET</span><span>POSITION</span><span>ENTRY → STOP → TARGET</span><span>MARGIN / RISK</span><span>STATUS</span></div>{orders.map(order=><div className="paper-row" key={order.id}><span><b>{order.id}</b><small>{new Date(order.createdAt).toLocaleString("en-IN")}</small></span><span><b>{order.symbol}</b><small>{order.market} · {order.product}</small></span><span><b className={order.side==="BUY"?"positive":"negative"}>{order.side==="BUY"?"LONG / BUY":"SHORT / SELL"}</b><small>{order.quantity} units · {order.leverage}×</small></span><span><b>{order.entry} → {order.stop} → {order.target}</b><small>{order.orderType.replace("_"," ")} · {order.marginMode}</small></span><span><b>{order.market==="NSE"?inr(order.margin):usd(order.margin)}</b><small>risk {order.market==="NSE"?inr(order.risk):usd(order.risk)}</small></span><span><em className={`paper-status ${order.status.toLowerCase()}`}>{order.status}</em>{order.status==="OPEN"&&<div><button onClick={()=>updateStatus(order.id,"CLOSED")}>CLOSE</button><button onClick={()=>updateStatus(order.id,"CANCELLED")}>CANCEL</button></div>}</span></div>)}</div>:<div className="empty-book"><strong>No paper positions yet.</strong><p>Build a validated order ticket to rehearse spot or futures execution.</p><button onClick={()=>setTab("TICKET")}>OPEN ORDER TICKET →</button></div>}</article>}
    {tab==="WATCHLIST"&&<article className="panel paper-book"><div className="paper-head"><div><p className="panel-kicker">MULTI-ASSET WATCHLIST</p><h3>Tracked instruments</h3></div></div>{watchlist.length?<div className="watch-grid">{watchlist.map(key=>{const [source,ticker]=key.split(":");const row=(source==="NSE"?stocks:coins).find(item=>item.symbol===ticker);return <button key={key} onClick={()=>{setMarket(source as Market);setSymbol(ticker);setProduct("SPOT");setTab("TICKET")}}><span>{source}</span><strong>{ticker}</strong><small>{row?.signal} · score {row?.score}/100</small><em onClick={event=>{event.stopPropagation();setWatchlist(current=>current.filter(item=>item!==key))}}>REMOVE ×</em></button>})}</div>:<div className="empty-book"><strong>Your watchlist is empty.</strong><p>Add an instrument from the order ticket.</p><button onClick={()=>setTab("TICKET")}>BROWSE INSTRUMENTS →</button></div>}</article>}
    <div className="trade-disclosure"><b>SAFETY GATE</b><span>This lab creates device-local simulations only. It does not transmit orders, hold API keys, calculate tax, or replace exchange/broker margin systems. Short selling and derivatives can lose more than the initial margin.</span></div>
    {confirm&&<div className="paper-confirm-layer" onMouseDown={event=>event.target===event.currentTarget&&setConfirm(undefined)}><aside role="dialog" aria-modal="true"><span>● PAPER ORDER ACCEPTED</span><button onClick={()=>setConfirm(undefined)}>×</button><h3>{confirm.side==="BUY"?"LONG / BUY":"SHORT / SELL"} {confirm.symbol}</h3><p>{confirm.product} · {confirm.orderType.replace("_"," ")} · {confirm.quantity} units · {confirm.leverage}×</p><strong>Risk locked at {confirm.market==="NSE"?inr(confirm.risk):usd(confirm.risk)}</strong><small>No order was sent to a broker or exchange.</small></aside></div>}
  </section>;
}
