"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type FuturesQuote={markPrice:number;indexPrice:number;fundingRate:number;nextFundingTime:number;openInterest:number;observedAt:string};
type Stock={symbol:string;company:string;price:number;change:number;score:number;signal:string};
type Coin={symbol:string;name:string;price:number;change24h:number;volatility?:number;score:number;signal:string;futures?:FuturesQuote};
type Market="NSE"|"CRYPTO";type Product="SPOT"|"FUTURES";type Horizon="INTRADAY"|"SWING"|"POSITIONAL";
type Plan={bias:string;confidence:number;current:number;entryLow:number;entryHigh:number;confirmation:number;stop:number;target1:number;target2:number;breakdown:number;shortEntry:number;shortStop:number;shortTarget1:number;shortTarget2:number;riskDistance:number;leverage:number;reason:string;invalidation:string};
type Timeframe="1m"|"5m"|"15m"|"1h"|"4h"|"1d";
type TimeframeSignal={timeframe:Timeframe;close:number;momentum:number;state:"BULLISH"|"BEARISH"|"NEUTRAL";strength:number};
type LiveTick={price:number;at:number};

const TIMEFRAMES:Timeframe[]=["1m","5m","15m","1h","4h","1d"];

const usd=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value<10?3:2}).format(value||0);
const inr=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value||0);
const compact=(value:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:2}).format(value||0);
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));

async function getFuturesQuote(symbol:string):Promise<FuturesQuote>{const contract=`${symbol}USDT`;const[premium,interest]=await Promise.all([fetch(`https://fapi.binance.com/fapi/v1/premiumIndex?symbol=${contract}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()),fetch(`https://fapi.binance.com/fapi/v1/openInterest?symbol=${contract}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject())]);return{markPrice:Number(premium.markPrice),indexPrice:Number(premium.indexPrice),fundingRate:Number(premium.lastFundingRate)*100,nextFundingTime:Number(premium.nextFundingTime),openInterest:Number(interest.openInterest),observedAt:new Date().toISOString()}}

async function getTimeframeSignals(symbol:string,product:Product):Promise<TimeframeSignal[]>{
  const base=product==="FUTURES"?"https://fapi.binance.com/fapi/v1/klines":"https://api.binance.com/api/v3/klines";
  return Promise.all(TIMEFRAMES.map(async timeframe=>{const response=await fetch(`${base}?symbol=${symbol}USDT&interval=${timeframe}&limit=60`,{cache:"no-store"});if(!response.ok)throw new Error("Candle feed unavailable");const rows=await response.json() as unknown[][];const closes=rows.map(row=>Number(row[4])).filter(Number.isFinite);if(closes.length<50)throw new Error("Insufficient candles");const close=closes.at(-1)??0,sma20=closes.slice(-20).reduce((a,b)=>a+b,0)/20,sma50=closes.slice(-50).reduce((a,b)=>a+b,0)/50,anchor=closes.at(-6)??close,momentum=anchor?((close/anchor)-1)*100:0;const state=close>sma20&&sma20>sma50&&momentum>0?"BULLISH":close<sma20&&sma20<sma50&&momentum<0?"BEARISH":"NEUTRAL";const strength=Math.round(clamp(50+Math.abs(momentum)*8+Math.abs(close/sma20-1)*500,50,99));return{timeframe,close,momentum,state,strength}}));
}

function createPlan(price:number,score:number,move:number,volatility:number,product:Product,horizon:Horizon):Plan{
  const horizonFactor=horizon==="INTRADAY"?.62:horizon==="SWING"?1:1.55;
  const vol=clamp((Math.max(Math.abs(move),volatility||0)+1.1)*horizonFactor,1.15,9.5);
  const pullback=clamp(vol*.0055,.007,.045),breakout=clamp(vol*.0038,.005,.032),riskPct=clamp(vol*.0085,.014,.075)*(product==="FUTURES"?.82:1);
  const entryHigh=price*(1-pullback*.42),entryLow=price*(1-pullback*1.18),confirmation=price*(1+breakout),stop=entryLow*(1-riskPct);
  const longRisk=confirmation-stop,breakdown=price*(1-breakout),shortEntry=price*(1-breakout*1.12),shortStop=price*(1+riskPct*.92),shortRisk=shortStop-shortEntry;
  const bias=score>=72&&move>=-.6?"BULLISH":score<=52||move<-2?"BEARISH":"NEUTRAL / WAIT";
  const confidence=Math.round(clamp(48+Math.abs(score-60)*.65+Math.min(10,Math.abs(move)*2),48,88));
  const leverage=product==="FUTURES"?Math.round(clamp(7-vol*.65,2,6)):1;
  return{bias,confidence,current:price,entryLow,entryHigh,confirmation,stop,target1:confirmation+longRisk*1.5,target2:confirmation+longRisk*2.5,breakdown,shortEntry,shortStop,shortTarget1:shortEntry-shortRisk*1.5,shortTarget2:shortEntry-shortRisk*2.5,riskDistance:longRisk,leverage,reason:bias==="BULLISH"?"Score and momentum favour buying controlled pullbacks or a confirmed breakout.":bias==="BEARISH"?"Weak score or momentum favours capital protection; futures shorts require breakdown confirmation.":"The edge is not strong enough. Wait for either the long confirmation or short breakdown level.",invalidation:bias==="BULLISH"?"A close below the protective stop invalidates the long setup.":bias==="BEARISH"?"A close above the short stop invalidates the bearish setup.":"Do not enter while price remains between the two confirmation levels."};
}

function Level({label,value,note,tone,format}:{label:string;value:number;note:string;tone?:string;format:(n:number)=>string}){return <div className={`decision-level ${tone??""}`}><span>{label}</span><strong>{format(value)}</strong><small>{note}</small></div>}

export default function TradingDesk({stocks,coins}:{stocks:Stock[];coins:Coin[]}){
  const[market,setMarket]=useState<Market>("NSE"),[product,setProduct]=useState<Product>("SPOT"),[horizon,setHorizon]=useState<Horizon>("SWING"),[symbol,setSymbol]=useState(stocks[0]?.symbol??"HDFCBANK"),[quote,setQuote]=useState<FuturesQuote>(),[quoteState,setQuoteState]=useState("SPOT PRICE REFERENCE"),[account,setAccount]=useState("500000"),[riskPct,setRiskPct]=useState("1"),[liveTick,setLiveTick]=useState<LiveTick>(),[streamState,setStreamState]=useState("NSE BROKER FEED REQUIRED"),[timeframes,setTimeframes]=useState<TimeframeSignal[]>([]),[timeframeState,setTimeframeState]=useState("NSE BROKER FEED REQUIRED"),[timeframeUpdatedAt,setTimeframeUpdatedAt]=useState<number>();
  const latestPrice=useRef<number|undefined>(undefined),reconnectTimer=useRef<number|undefined>(undefined);
  const instruments=market==="NSE"?stocks:coins,instrument=useMemo(()=>instruments.find(item=>item.symbol===symbol)??instruments[0],[instruments,symbol]);
  const name=instrument?("company"in instrument?instrument.company:instrument.name):"",move=instrument?("change"in instrument?instrument.change:instrument.change24h):0,volatility=instrument&&"volatility"in instrument?instrument.volatility??0:0;
  const archived=market==="CRYPTO"&&instrument&&"futures"in instrument?instrument.futures:undefined;
  const referencePrice=market==="CRYPTO"&&liveTick?.price?liveTick.price:product==="FUTURES"&&quote?.markPrice?quote.markPrice:instrument?.price??0,plan=useMemo(()=>createPlan(referencePrice,instrument?.score??50,move,volatility,product,horizon),[referencePrice,instrument?.score,move,volatility,product,horizon]);
  const format=market==="NSE"?inr:usd,capital=Number(account)||0,riskBudget=capital*(Number(riskPct)||0)/100,longQty=plan.riskDistance>0?riskBudget/plan.riskDistance:0,shortRisk=Math.max(.000001,plan.shortStop-plan.shortEntry),shortQty=riskBudget/shortRisk;
  const consensus=useMemo(()=>{const bullish=timeframes.filter(item=>item.state==="BULLISH").length,bearish=timeframes.filter(item=>item.state==="BEARISH").length,neutral=timeframes.length-bullish-bearish,higher=timeframes.filter(item=>["1h","4h","1d"].includes(item.timeframe));const higherBull=higher.every(item=>item.state!=="BEARISH"),higherBear=higher.every(item=>item.state!=="BULLISH");return{bullish,bearish,neutral,label:bullish>=4&&higherBull?"LONG CONFIRMED":bearish>=4&&higherBear?"SHORT CONFIRMED":"WAIT / MIXED"}},[timeframes]);

  useEffect(()=>{const next=(market==="NSE"?stocks:coins)[0];if(next){setSymbol(next.symbol);setQuote(undefined)}},[market,stocks,coins]);
  useEffect(()=>{if(!(market==="CRYPTO"&&product==="FUTURES")){setQuote(undefined);setQuoteState(product==="FUTURES"?"NSE CONTRACT FEED REQUIRED":"SPOT PRICE REFERENCE");return}if(archived){setQuote(archived);setQuoteState("10-MINUTE FUTURES ARCHIVE")}let active=true;const refresh=()=>getFuturesQuote(symbol).then(value=>{if(active){setQuote(value);setQuoteState("LIVE PUBLIC FUTURES METRICS")}}).catch(()=>active&&setQuoteState(archived?"ARCHIVED SNAPSHOT · LIVE RETRYING":"PUBLIC FUTURES FEED UNAVAILABLE"));refresh();const timer=window.setInterval(refresh,30_000);return()=>{active=false;window.clearInterval(timer)}},[market,product,symbol,archived]);
  useEffect(()=>{latestPrice.current=undefined;setLiveTick(undefined);if(market!=="CRYPTO"){setStreamState("NSE BROKER FEED REQUIRED");return}let active=true,socket:WebSocket|undefined;const connect=()=>{setStreamState("CONNECTING");const channel=product==="FUTURES"?`wss://fstream.binance.com/ws/${symbol.toLowerCase()}usdt@markPrice@1s`:`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}usdt@trade`;socket=new WebSocket(channel);socket.onopen=()=>active&&setStreamState(product==="FUTURES"?"BINANCE MARK PRICE · 1S":"BINANCE TRADES · 1S DISPLAY");socket.onmessage=event=>{try{const payload=JSON.parse(event.data) as {p?:string};const price=Number(payload.p);if(active&&Number.isFinite(price)&&price>0)latestPrice.current=price}catch{}};socket.onerror=()=>socket?.close();socket.onclose=()=>{if(active){setStreamState("RECONNECTING");reconnectTimer.current=window.setTimeout(connect,2500)}}};connect();const displayTimer=window.setInterval(()=>{if(active&&latestPrice.current)setLiveTick({price:latestPrice.current,at:Date.now()})},1000);return()=>{active=false;window.clearInterval(displayTimer);if(reconnectTimer.current)window.clearTimeout(reconnectTimer.current);socket?.close()}},[market,product,symbol]);
  useEffect(()=>{if(market!=="CRYPTO"){setTimeframes([]);setTimeframeState("NSE BROKER FEED REQUIRED");setTimeframeUpdatedAt(undefined);return}let active=true;const refresh=()=>{setTimeframeState(current=>current.includes("LIVE")?current:"LOADING SIX TIMEFRAMES");getTimeframeSignals(symbol,product).then(value=>{if(active){setTimeframes(value);setTimeframeState("LIVE CANDLE ANALYSIS");setTimeframeUpdatedAt(Date.now())}}).catch(()=>active&&setTimeframeState(timeframes.length?"LAST GOOD CANDLES · RETRYING":"CANDLE FEED UNAVAILABLE"))};refresh();const timer=window.setInterval(refresh,60_000);return()=>{active=false;window.clearInterval(timer)}},[market,product,symbol]);
  const switchMarket=(next:Market)=>{setMarket(next);setProduct("SPOT")};
  return <section className="trade-lab execution-planner" id="trading">
    <div className="trade-hero"><div><p className="panel-kicker">MULTI-ASSET ENTRY / EXIT ENGINE</p><h2>When to buy, sell, long or short</h2><p>Select a security and timeframe to generate exact model levels. A level becomes actionable only after its stated confirmation condition is satisfied.</p></div><div className="execution-lock planning"><i/>PLANNING ONLY<small>No order ledger · no automatic orders</small></div></div>
    <div className="trade-switchboard"><div className="segmented"><button className={market==="NSE"?"active":""} onClick={()=>switchMarket("NSE")}>NSE INDIA</button><button className={market==="CRYPTO"?"active":""} onClick={()=>switchMarket("CRYPTO")}>CRYPTO 24/7</button></div><div className="segmented"><button className={product==="SPOT"?"active":""} onClick={()=>setProduct("SPOT")}>SPOT</button><button className={product==="FUTURES"?"active":""} onClick={()=>setProduct("FUTURES")}>FUTURES</button></div><div className="segmented horizon-selector">{(["INTRADAY","SWING","POSITIONAL"]as Horizon[]).map(item=><button key={item} className={horizon===item?"active":""} onClick={()=>setHorizon(item)}>{item}</button>)}</div></div>
    <div className="planner-selector panel"><label>SECURITY / COIN<select value={symbol} onChange={event=>{setSymbol(event.target.value);setQuote(undefined)}}>{instruments.map(item=><option value={item.symbol} key={item.symbol}>{item.symbol} · {"company"in item?item.company:item.name}</option>)}</select></label><div><span>CURRENT REFERENCE</span><strong className={market==="CRYPTO"&&liveTick?"live-price":""}>{format(referencePrice)}</strong><small className={market==="CRYPTO"?"stream-caption":move>=0?"positive":"negative"}>{market==="CRYPTO"?streamState:`${move>=0?"+":""}${move.toFixed(2)}% · licensed feed pending`}</small></div><div><span>MODEL BIAS</span><strong className={plan.bias==="BULLISH"?"positive":plan.bias==="BEARISH"?"negative":""}>{plan.bias}</strong><small>{plan.confidence}% setup confidence</small></div><div><span>MODEL / SIGNAL</span><strong>{instrument?.score}/100</strong><small>{instrument?.signal} · {name}</small></div></div>
    <div className="decision-summary"><i className={plan.bias.toLowerCase().split(" ")[0]}/><div><span>CURRENT DECISION</span><strong>{plan.bias==="BULLISH"?"Prefer the buy/long plan; do not chase between levels.":plan.bias==="BEARISH"?"Avoid spot buying; consider only a confirmed futures breakdown.":"WAIT — neither side has confirmation yet."}</strong><p>{plan.reason}</p></div></div>
    <article className="panel timeframe-console"><div className="timeframe-head"><div><p className="panel-kicker">MULTI-TIMEFRAME CONFIRMATION</p><h3>All trading horizons, checked together</h3><p>1m through 1d structure is recalculated from the latest closed and active candles. Price above updates once per second.</p></div><div className={`consensus-badge ${consensus.label.toLowerCase().split(" ")[0]}`}><span>{market==="CRYPTO"?consensus.label:"FEED REQUIRED"}</span><small>{timeframeState}{timeframeUpdatedAt?` · ${new Date(timeframeUpdatedAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}`:""}</small></div></div><div className="timeframe-grid">{TIMEFRAMES.map(timeframe=>{const signal=timeframes.find(item=>item.timeframe===timeframe);return <div className={`timeframe-cell ${signal?.state.toLowerCase()??"pending"}`} key={timeframe}><span>{timeframe}</span>{signal?<><strong>{signal.state}</strong><b>{signal.momentum>=0?"+":""}{signal.momentum.toFixed(2)}%</b><small>{format(signal.close)} · {signal.strength}%</small></>:<><strong>{market==="CRYPTO"?"LOADING":"BROKER FEED"}</strong><b>—</b><small>{market==="CRYPTO"?"Awaiting candles":"Licensed OHLC required"}</small></>}</div>})}</div><div className="consensus-line"><span><i className="bull-dot"/>Bullish {consensus.bullish}/6</span><span><i className="neutral-dot"/>Neutral {consensus.neutral}/6</span><span><i className="bear-dot"/>Bearish {consensus.bearish}/6</span><b>{market==="CRYPTO"?"A trade is confirmed only with 4/6 alignment and no opposing 1h, 4h or 1d structure.":"NSE second-by-second and candle confirmation activates when a licensed broker WebSocket is connected."}</b></div></article>
    <div className="scenario-grid">
      <article className="panel scenario-card long-card"><div className="scenario-head"><div><p className="panel-kicker">{product==="SPOT"?"SPOT BUY PLAN":"FUTURES LONG PLAN"}</p><h3>When to buy / long</h3></div><span>01</span></div><div className="condition-banner"><b>ACT ONLY IF</b>{product==="SPOT"?`price enters the accumulation zone and holds, or closes above ${format(plan.confirmation)} with volume.`:`price closes above ${format(plan.confirmation)} and the next candle holds that level.`}</div><div className="level-grid"><Level label="PREFERRED ENTRY LOW" value={plan.entryLow} note="Stagger first entry" format={format}/><Level label="PREFERRED ENTRY HIGH" value={plan.entryHigh} note="Do not chase above this zone" format={format}/><Level label="BREAKOUT CONFIRMATION" value={plan.confirmation} note="Close above, then hold" tone="cyan" format={format}/><Level label="PROTECTIVE STOP" value={plan.stop} note="Exit if candle closes below" tone="red" format={format}/><Level label="TARGET 1" value={plan.target1} note="Book 40–50%; move stop" tone="green" format={format}/><Level label="TARGET 2" value={plan.target2} note="Trail the remaining position" tone="green" format={format}/></div><div className="exit-rule"><b>WHEN TO SELL</b><p>Book part at Target 1. Exit the remainder at Target 2, on a close below the revised trailing stop, or immediately if the thesis becomes invalid.</p></div></article>
      <article className="panel scenario-card short-card"><div className="scenario-head"><div><p className="panel-kicker">{product==="SPOT"?"SPOT SELL / AVOID PLAN":"FUTURES SHORT PLAN"}</p><h3>{product==="SPOT"?"When to sell or avoid":"When to short"}</h3></div><span>02</span></div><div className="condition-banner danger"><b>ACT ONLY IF</b>{product==="SPOT"?`price closes below ${format(plan.breakdown)}, the stop is breached, or the model signal falls to REDUCE / AVOID.`:`price closes below ${format(plan.shortEntry)} and the next candle fails to reclaim the breakdown.`}</div><div className="level-grid"><Level label={product==="SPOT"?"SELL / RISK BREAKDOWN":"SHORT CONFIRMATION"} value={plan.shortEntry} note="Requires a confirmed close" tone="red" format={format}/><Level label={product==="SPOT"?"HARD EXIT":"SHORT ENTRY LIMIT"} value={product==="SPOT"?plan.stop:plan.breakdown} note={product==="SPOT"?"Capital-protection level":"Avoid chasing below this"} tone="red" format={format}/><Level label="SHORT INVALIDATION" value={plan.shortStop} note="Close short above this price" tone="amber" format={format}/><Level label="SHORT TARGET 1" value={plan.shortTarget1} note="Cover 40–50%; move stop" tone="green" format={format}/><Level label="SHORT TARGET 2" value={plan.shortTarget2} note="Trail the remaining position" tone="green" format={format}/><Level label="NO-TRADE MIDPOINT" value={(plan.confirmation+plan.shortEntry)/2} note="Wait while price is near here" format={format}/></div><div className="exit-rule"><b>{product==="SPOT"?"RE-ENTRY RULE":"WHEN TO COVER"}</b><p>{product==="SPOT"?`Consider buying again only after price reclaims ${format(plan.confirmation)} and the score stabilises above 60.`:"Cover part at Short Target 1. Exit the remainder at Short Target 2 or if price closes above the short invalidation level."}</p></div></article>
    </div>
    <div className="planner-bottom"><article className="panel sizing-card"><p className="panel-kicker">RISK-SIZED EXECUTION</p><h3>How much to buy or short</h3><div className="risk-inputs"><label>CAPITAL<input value={account} inputMode="decimal" onChange={event=>setAccount(event.target.value)}/></label><label>MAX RISK<input value={riskPct} inputMode="decimal" onChange={event=>setRiskPct(event.target.value)}/><span>%</span></label></div><dl><div><dt>Maximum defined loss</dt><dd>{format(riskBudget)}</dd></div><div><dt>Suggested long quantity</dt><dd>{longQty.toFixed(market==="CRYPTO"?4:0)}</dd></div><div><dt>Suggested short quantity</dt><dd>{shortQty.toFixed(market==="CRYPTO"?4:0)}</dd></div><div><dt>Model leverage ceiling</dt><dd>{product==="FUTURES"?`${plan.leverage}×`:"1× / cash"}</dd></div></dl><small>Quantity is based on the distance between entry and invalidation. NSE futures quantities must be rounded to the current exchange lot size.</small></article>
      <article className="panel checklist-card"><p className="panel-kicker">BEFORE YOU ACT</p><h3>Confirmation checklist</h3><ul><li><i/>The entry or breakdown level has closed—not merely touched.</li><li><i/>The following candle has not immediately invalidated the move.</li><li><i/>Position size keeps the defined loss within {riskPct||"1"}% of capital.</li><li><i/>No major result, policy decision or funding event is imminent.</li><li><i/>For futures, mark price and spot/index price are not abnormally divergent.</li></ul><div className="invalidation-box"><b>INVALIDATION</b><span>{plan.invalidation}</span></div></article>
      <article className="panel telemetry"><div className="telemetry-head"><div><p className="panel-kicker">MARKET TELEMETRY</p><h3>{quoteState}</h3></div><i className={quote?"online":""}/></div>{market==="CRYPTO"&&product==="FUTURES"&&quote?<dl><div><dt>Mark price</dt><dd>{usd(quote.markPrice)}</dd></div><div><dt>Index price</dt><dd>{usd(quote.indexPrice)}</dd></div><div><dt>Basis</dt><dd>{((quote.markPrice/quote.indexPrice-1)*100).toFixed(3)}%</dd></div><div><dt>Funding / 8H</dt><dd className={quote.fundingRate>=0?"positive":"negative"}>{quote.fundingRate.toFixed(4)}%</dd></div><div><dt>Open interest</dt><dd>{compact(quote.openInterest)} {symbol}</dd></div><div><dt>Next funding</dt><dd>{new Date(quote.nextFundingTime).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</dd></div></dl>:<div className="telemetry-empty"><strong>{product==="SPOT"?"Select FUTURES for derivatives telemetry.":"Contract-data adapter ready."}</strong><p>{market==="NSE"?"Live NSE contract, lot-size, margin and open-interest values require an authorised broker or licensed feed.":"Public futures metrics refresh every 30 seconds when available."}</p></div>}</article></div>
    <div className="trade-disclosure"><b>MODEL LEVELS</b><span>These prices are derived from the current dashboard reference, momentum, score, volatility and selected horizon. They update when source prices update. They are not guaranteed fills or investment advice; verify every price with your broker or exchange before acting.</span></div>
  </section>;
}
