"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import IntelligenceGlobe from "./components/IntelligenceGlobe";
import CryptoSection, { type CryptoDashboard } from "./components/CryptoSection";
import seedData from "../public/data/dashboard.json";

type Horizon = "short" | "long";
type Period = "1W" | "1M" | "3M" | "1Y";
type Signal = "ACCUMULATE" | "HOLD" | "REDUCE" | "AVOID" | "WATCH";
type Stock = { symbol:string; company:string; sector:string; price:number; change:number; signal:Signal; confidence:number; score:number; allocation:number; rationale:string; risk:string; spark:number[] };
type IntelligenceEvent = { id:string; timestamp:string; publishedAt?:string; observedAt?:string; eventAt?:string; region:string; title:string; source:string; sourceUrl?:string; status:"CONFIRMED"|"DEVELOPING"|"DISPUTED"; impact:"POSITIVE"|"NEGATIVE"|"MIXED"; companies:string[]; summary:string; sourceCount?:number; confirmationBasis?:string; isInference?:boolean };
type Sector = { name:string; score:number; change:number };
type DashboardData = { generatedAt:string; dataMode?:string; market:{ regime:string; score:number; nifty:number; niftyChange:number; vix:number; breadth:number }; portfolio:{ value:number; dayChange:number; totalReturn:number; maxDrawdown:number; cash:number; history:number[]; historyByPeriod?:Partial<Record<Period,number[]>> }; shortTerm:Stock[]; longTerm:Stock[]; events:IntelligenceEvent[]; sectors:Sector[]; crypto?:CryptoDashboard };
type Report = { kind:"stock"; item:Stock } | { kind:"event"; item:IntelligenceEvent } | { kind:"sector"; item:Sector };

const initialData = seedData as DashboardData;
const PERIOD_LABELS:Record<Period,string[]> = { "1W":["MON","TUE","WED","THU","FRI"], "1M":["W1","W2","W3","W4","NOW"], "3M":["JUN","JUL","AUG","SEP","NOW"], "1Y":["Q3","Q4","Q1","Q2","NOW"] };
const SECTOR_HORIZONS:Record<string,[number,number,number,number]> = { "Capital Goods":[.7,2.1,3.8,11.4], Financials:[.3,1.5,2.4,8.1], Telecom:[.8,1.7,2.1,9.6], Healthcare:[-.2,.6,1.2,5.4], Technology:[-.6,-.4,-.8,1.2], Metals:[-1.1,-2,-2.7,-6.3] };

function formatINR(value:number, compact=false) { return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:compact?0:2,notation:compact?"compact":"standard"}).format(value); }
function timeAgo(timestamp:string,reference:string){const m=Math.max(1,Math.floor((new Date(reference).getTime()-new Date(timestamp).getTime())/60000));if(m<60)return`${m}m ago`;const h=Math.floor(m/60);return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`;}
function Sparkline({values,positive=true}:{values:number[];positive?:boolean}){const w=120,h=36,min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),pts=values.map((v,i)=>`${i/(values.length-1)*w},${h-(v-min)/range*h}`).join(" ");return <svg className="sparkline" viewBox={`0 0 ${w} ${h}`} aria-hidden="true"><polyline points={pts} fill="none" stroke={positive?"#9eff7a":"#ff7a91"} strokeWidth="2.5"/></svg>;}
function PortfolioChart({values,period}:{values:number[];period:Period}){const w=720,h=180,min=Math.min(...values)*.995,max=Math.max(...values)*1.005,range=Math.max(1,max-min),pts=values.map((v,i)=>`${i/(values.length-1)*w},${h-(v-min)/range*h}`).join(" ");return <svg className="portfolio-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Portfolio value for ${period}`}><defs><linearGradient id="portfolioFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#c7ff4a" stopOpacity=".3"/><stop offset="100%" stopColor="#c7ff4a" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(n=><line key={n} x1="0" x2={w} y1={h/3*n} y2={h/3*n} stroke="rgba(255,255,255,.08)"/>)}<polygon points={`0,${h} ${pts} ${w},${h}`} fill="url(#portfolioFill)"/><polyline points={pts} fill="none" stroke="#c7ff4a" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/></svg>;}

function EvidenceRow({event,onClick}:{event:IntelligenceEvent;onClick?:()=>void}){
  const content=<><span className={`status-dot ${event.status.toLowerCase()}`}/><span><b>{event.title}</b><small>{event.source} · {event.sourceCount??1} source(s)</small></span><em>{event.sourceUrl?"OPEN SOURCE ↗":event.status}</em></>;
  return event.sourceUrl?<a className="evidence-row" href={event.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Open original source for ${event.title}`}>{content}</a>:<button className="evidence-row" onClick={onClick}>{content}</button>;
}

function EvidenceReport({report,data,onClose}:{report:Report;data:DashboardData;onClose:()=>void}){
  const stockEvents=report.kind==="stock"?data.events.filter(e=>e.companies.includes(report.item.symbol)):[];
  const scoreParts=report.kind==="stock"?[["Fundamentals",Math.min(94,report.item.score+5)],["Price momentum",Math.max(28,report.item.score+report.item.change*4)],["Evidence quality",report.item.confidence],["Risk control",Math.max(30,100-report.item.allocation*4)]] as [string,number][]:[];
  const sectorH=report.kind==="sector"?(SECTOR_HORIZONS[report.item.name]??[0,0,report.item.change,report.item.change*2]):[0,0,0,0];
  return <div className="report-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="report-drawer" role="dialog" aria-modal="true"><button className="report-close" onClick={onClose}>CLOSE ×</button>
    {report.kind==="stock"&&<><p className="panel-kicker">FULL DECISION EVIDENCE / {report.item.sector}</p><h2>{report.item.symbol} <small>{report.item.company}</small></h2><div className="report-verdict"><em className={`signal ${report.item.signal.toLowerCase()}`}>{report.item.signal}</em><strong>{report.item.score}/100</strong><span>{report.item.confidence}% confidence</span></div><section><h3>Decision thesis</h3><p>{report.item.rationale}</p><div className="two-col"><div><b>BULL CASE</b><p>Execution remains aligned with the identified catalyst and the composite score stays above 70.</p></div><div className="risk-copy"><b>BEAR / INVALIDATION</b><p>{report.item.risk}</p></div></div></section><section><h3>Model anatomy</h3>{scoreParts.map(([label,value])=><div className="metric-line" key={label}><span>{label}</span><i><u style={{width:`${value}%`}}/></i><b>{Math.round(value)}</b></div>)}<small className="method-note">Model-derived assessment — not a reported company fact.</small></section><section><h3>Execution plan</h3><dl className="report-grid"><div><dt>Model allocation</dt><dd>{report.item.allocation}%</dd></div><div><dt>Review cadence</dt><dd>{report.item.signal==="ACCUMULATE"?"Weekly":"Daily"}</dd></div><div><dt>Entry</dt><dd>Wait for live-price validation</dd></div><div><dt>Hard invalidation</dt><dd>Risk thesis + score below 60</dd></div></dl></section><section><h3>Cross-referenced evidence</h3>{stockEvents.length?stockEvents.map(e=><EvidenceRow event={e} key={e.id}/>):<p className="empty-note">No verified event is mapped to this security. The score receives no news-evidence boost.</p>}</section></>}
    {report.kind==="event"&&<><p className="panel-kicker">EVENT IMPACT DOSSIER / {report.item.region}</p><h2>{report.item.title}</h2>{report.item.sourceUrl&&<a className="report-primary-link" href={report.item.sourceUrl} target="_blank" rel="noreferrer">VISIT ORIGINAL NEWS WEBSITE ↗</a>}<div className="report-verdict"><em className={report.item.status.toLowerCase()}>{report.item.status}</em><strong>{report.item.impact}</strong><span>{report.item.sourceCount??1} source{(report.item.sourceCount??1)!==1?"s":""}</span></div><section><h3>Verified record</h3><p>{report.item.summary}</p><dl className="report-grid"><div><dt>Event time</dt><dd>{new Date(report.item.eventAt??report.item.timestamp).toLocaleString()}</dd></div><div><dt>Published</dt><dd>{new Date(report.item.publishedAt??report.item.timestamp).toLocaleString()}</dd></div><div><dt>Observed by system</dt><dd>{new Date(report.item.observedAt??data.generatedAt).toLocaleString()}</dd></div><div><dt>Verification</dt><dd>{report.item.confirmationBasis??"Pending corroboration"}</dd></div></dl></section><section><h3>Market linkage</h3><p><span className="inference-badge">INFERENCE</span> The {report.item.impact.toLowerCase()} impact label and affected securities are model mappings, not claims made by the source.</p><div className="company-tags report-tags">{report.item.companies.map(c=><span key={c}>{c}</span>)}</div></section><section><h3>Source trail</h3>{report.item.sourceUrl?<a className="source-link" href={report.item.sourceUrl} target="_blank" rel="noreferrer">OPEN ORIGINAL SOURCE ↗</a>:<p className="empty-note">Seed demonstration record. Without an original source this record cannot become Confirmed.</p>}</section></>}
    {report.kind==="sector"&&<><p className="panel-kicker">SECTOR INTELLIGENCE REPORT / 30D MODEL</p><h2>{report.item.name}</h2><div className="report-verdict"><strong>{report.item.score}/100</strong><span className={report.item.change>=0?"positive":"negative"}>{report.item.change>=0?"+":""}{report.item.change}% relative move</span><em className="signal watch">{report.item.score>=70?"LEADING":report.item.score<50?"LAGGING":"NEUTRAL"}</em></div><section><h3>Relative performance</h3><div className="horizon-grid">{["1D","1W","1M","3M"].map((label,i)=><div key={label}><span>{label}</span><b className={sectorH[i]>=0?"positive":"negative"}>{sectorH[i]>=0?"+":""}{sectorH[i]}%</b></div>)}</div><small className="method-note">Illustrative model series until a licensed sector-price feed is connected.</small></section><section><h3>Rotation diagnosis</h3><dl className="report-grid"><div><dt>Breadth</dt><dd>{report.item.score>=70?"Broad participation":"Narrow / weakening"}</dd></div><div><dt>Institutional flow</dt><dd>Awaiting licensed feed</dd></div><div><dt>Earnings revisions</dt><dd>{report.item.change>=0?"Improving bias":"Deteriorating bias"}</dd></div><div><dt>Valuation</dt><dd>Historical feed required</dd></div></dl></section><section><h3>Leaders, risks and action</h3><p><b>Mapped leaders:</b> {data.longTerm.concat(data.shortTerm).filter(s=>s.sector===report.item.name).map(s=>s.symbol).join(", ")||"No covered security"}.</p><p><b>Short-term:</b> {report.item.score>=70?"Prefer leaders on controlled pullbacks.":"Avoid chasing until breadth improves."}</p><p><b>Long-term:</b> {report.item.score>=65?"Build only where company fundamentals confirm sector strength.":"Keep allocation below benchmark pending reversal."}</p><p className="risk-copy"><b>Invalidation:</b> 30D score crosses {report.item.score>=65?"below 60":"above 60"} with breadth confirmation.</p></section></>}
  </aside></div>;
}

export default function Home(){
  const [data,setData]=useState<DashboardData>(initialData),[horizon,setHorizon]=useState<Horizon>("long"),[selected,setSelected]=useState(initialData.longTerm[0].symbol),[query,setQuery]=useState(""),[eventFilter,setEventFilter]=useState<"ALL"|"CONFIRMED"|"DEVELOPING"|"DISPUTED">("ALL"),[period,setPeriod]=useState<Period>("1M"),[report,setReport]=useState<Report|null>(null),[popover,setPopover]=useState<"alerts"|"profile"|null>(null),[selectedEvent,setSelectedEvent]=useState<IntelligenceEvent>(),[alertQueue,setAlertQueue]=useState<IntelligenceEvent[]>([]),[voiceEnabled,setVoiceEnabled]=useState(false);
  const knownEventIds=useRef(new Set(initialData.events.map(event=>event.id)));
  const voiceEnabledRef=useRef(false);
  const speakText=(text:string)=>{
    if(typeof window==="undefined"||!("speechSynthesis" in window))return;
    window.speechSynthesis.cancel();
    const utterance=new SpeechSynthesisUtterance(text),voices=window.speechSynthesis.getVoices();
    utterance.voice=voices.find(voice=>voice.lang==="en-IN")??voices.find(voice=>voice.lang.startsWith("en"))??null;
    utterance.rate=.9;utterance.pitch=.92;utterance.volume=.92;
    window.speechSynthesis.speak(utterance);
  };
  const toggleVoice=()=>{const next=!voiceEnabledRef.current;voiceEnabledRef.current=next;setVoiceEnabled(next);if(next)speakText("Voice intelligence online. Monitoring global market evidence.");else window.speechSynthesis?.cancel();};
  useEffect(()=>{
    const base=process.env.NEXT_PUBLIC_BASE_PATH??"";
    const refresh=()=>fetch(`${base}/data/dashboard.json?ts=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((fresh:DashboardData)=>{
      const incoming=fresh.events.filter(event=>!knownEventIds.current.has(event.id));
      fresh.events.forEach(event=>knownEventIds.current.add(event.id));
      setData(fresh);
      if(incoming.length)setAlertQueue(queue=>[...queue,...incoming.filter(event=>!queue.some(queued=>queued.id===event.id))]);
    }).catch(()=>undefined);
    refresh();
    const timer=window.setInterval(refresh,60_000);
    return()=>window.clearInterval(timer);
  },[]);
  const stocks=horizon==="long"?data.longTerm:data.shortTerm,filteredStocks=stocks.filter(s=>`${s.symbol} ${s.company} ${s.sector}`.toLowerCase().includes(query.toLowerCase())),selectedStock=stocks.find(s=>s.symbol===selected)??stocks[0],visibleEvents=data.events.filter(e=>eventFilter==="ALL"||e.status===eventFilter),updatedLabel=useMemo(()=>new Date(data.generatedAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}),[data.generatedAt]),history=data.portfolio.historyByPeriod?.[period]??data.portfolio.history;
  const changeHorizon=(next:Horizon)=>{setHorizon(next);setSelected((next==="long"?data.longTerm:data.shortTerm)[0].symbol)};
  const newsAlert=alertQueue[0],dismissNewsAlert=()=>setAlertQueue(queue=>queue.slice(1));
  useEffect(()=>{if(newsAlert&&voiceEnabledRef.current)speakText(`New market intelligence. ${newsAlert.region}. ${newsAlert.title}. Verification status, ${newsAlert.status.toLowerCase()}.`)},[newsAlert]);
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">W</div><div><strong>WORLD//MARKET</strong><span>INTELLIGENCE</span></div></div><nav className="nav-list"><a className="nav-item active" href="#overview"><span>01</span>Overview</a><a className="nav-item" href="#signals"><span>02</span>Signals</a><a className="nav-item" href="#intelligence"><span>03</span>Intelligence</a><a className="nav-item" href="#portfolio"><span>04</span>Portfolio</a><a className="nav-item" href="#crypto"><span>05</span>Crypto 24/7</a>
</nav><div className="sidebar-foot"><div className="system-state"><i/>RESEARCH ENGINE ONLINE</div><p>Last evidence cycle</p><strong>{updatedLabel}</strong><small>Decision support · not execution</small></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="eyebrow">DECISION TERMINAL / INDIA</p><h1>Market Intelligence</h1></div><div className="top-actions"><label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search securities" aria-label="Search securities"/></label><button className={`voice-button ${voiceEnabled?"active":""}`} onClick={toggleVoice} aria-pressed={voiceEnabled} aria-label="Toggle voice intelligence"><i/>{voiceEnabled?"VOICE ONLINE":"ARM VOICE"}</button><div className="action-wrap"><button className="icon-button" aria-label="Evidence alerts" onClick={()=>setPopover(popover==="alerts"?null:"alerts")}>◉<b>{data.events.filter(e=>e.status!=="CONFIRMED").length}</b></button>{popover==="alerts"&&<div className="action-popover"><strong>EVIDENCE ALERTS</strong>{data.events.slice(0,3).map(e=><button key={e.id} onClick={()=>{setReport({kind:"event",item:e});setPopover(null)}}><span>{e.status}</span>{e.title}</button>)}</div>}</div><div className="action-wrap"><button className="profile-button" aria-label="Research profile" onClick={()=>setPopover(popover==="profile"?null:"profile")}>GA</button>{popover==="profile"&&<div className="action-popover profile-pop"><strong>PERSONAL RESEARCH MODE</strong><p>India focus · Long & short horizon</p><p>Auto-trading: OFF</p><p>Evidence rule: 2-source or primary</p><p>Voice intelligence: {voiceEnabled?"ONLINE":"OFFLINE"}</p></div>}</div></div></header>
      <div className="content" id="overview"><div className="integrity-banner"><span>DATA INTEGRITY</span><strong>{data.dataMode??"DEMONSTRATION MARKET SNAPSHOT"}</strong><p>Facts require a primary source or two independent sources. Unverified events do not alter decision scores.</p></div><section className="market-strip"><article className="regime-card"><div><p>MARKET REGIME</p><strong>{data.market.regime}</strong></div><div className="regime-score"><span>{data.market.score}</span><small>/100</small></div></article><article><p>NIFTY 50 · SAMPLE SNAPSHOT</p><strong>{data.market.nifty.toLocaleString("en-IN")}</strong><span className={data.market.niftyChange>=0?"positive":"negative"}>▲ {data.market.niftyChange.toFixed(2)}%</span></article><article><p>INDIA VIX · SAMPLE SNAPSHOT</p><strong>{data.market.vix.toFixed(2)}</strong><span className="muted">LOW–MODERATE</span></article><article><p>MARKET BREADTH · MODEL</p><strong>{data.market.breadth}%</strong><span className="positive">ADVANCING</span></article></section>
      <section className="dashboard-grid"><article className="panel portfolio-panel" id="portfolio"><div className="panel-head"><div><p className="panel-kicker">PORTFOLIO VALUE / MODEL</p><h2>{formatINR(data.portfolio.value,true)}</h2></div><div className="period-tabs">{(["1W","1M","3M","1Y"] as Period[]).map(p=><button key={p} className={period===p?"active":""} onClick={()=>setPeriod(p)} aria-pressed={period===p}>{p}</button>)}</div></div><div className="portfolio-meta"><span className="positive">+{data.portfolio.dayChange}% today</span><span><b>+{data.portfolio.totalReturn}%</b> total return</span><span><b>{data.portfolio.maxDrawdown}%</b> max drawdown</span></div><PortfolioChart values={history} period={period}/><div className="chart-labels">{PERIOD_LABELS[period].map(x=><span key={x}>{x}</span>)}</div></article>
      <article className="panel world-panel"><div className="panel-head"><div><p className="panel-kicker">GLOBAL EVIDENCE ORBIT</p><h3>Click a signal to inspect its market impact</h3></div><span className="live-badge">● SCANNING</span></div><IntelligenceGlobe events={data.events} selectedId={selectedEvent?.id} onSelect={e=>setSelectedEvent(data.events.find(x=>x.id===e.id))}/>{selectedEvent&&<button className="globe-event-card" onClick={()=>setReport({kind:"event",item:selectedEvent})}><span>{selectedEvent.region} / {selectedEvent.status}</span><strong>{selectedEvent.title}</strong><small>{selectedEvent.companies.join(" · ")} · OPEN IMPACT DOSSIER →</small></button>}<div className="impact-legend"><span><i className="positive-dot"/>POSITIVE</span><span><i className="mixed-dot"/>MIXED</span><span><i className="negative-dot"/>NEGATIVE</span></div></article>
      <article className="panel signals-panel" id="signals"><div className="panel-head signal-heading"><div><p className="panel-kicker">NIFTY 50 LIQUID CORE · {data.longTerm.length+data.shortTerm.length} STOCKS</p><h3>Highest-conviction signals</h3><small className="universe-note">Large, liquid companies across sectors. Inclusion is for research coverage, not an automatic buy decision.</small></div>
<div className="horizon-toggle"><button className={horizon==="short"?"active":""} onClick={()=>changeHorizon("short")}>SHORT TERM</button><button className={horizon==="long"?"active":""} onClick={()=>changeHorizon("long")}>LONG TERM</button></div></div><div className="stock-table"><div className="stock-row stock-header"><span>SECURITY</span><span>PRICE / MOVE</span><span>TREND</span><span>DECISION</span><span>CONFIDENCE</span></div>{filteredStocks.map(stock=><button className={`stock-row ${selectedStock.symbol===stock.symbol?"selected":""}`} key={stock.symbol} onClick={()=>setSelected(stock.symbol)}><span className="security"><b>{stock.symbol}</b><small>{stock.company}</small></span><span><b>{formatINR(stock.price)}</b><small className={stock.change>=0?"positive":"negative"}>{stock.change>=0?"+":""}{stock.change}%</small></span><Sparkline values={stock.spark} positive={stock.change>=0}/><span><em className={`signal ${stock.signal.toLowerCase()}`}>{stock.signal}</em><small>{stock.score}/100 score</small></span><span className="confidence"><b>{stock.confidence}%</b><i><u style={{width:`${stock.confidence}%`}}/></i></span></button>)}</div></article>
      <aside className="panel thesis-panel"><div className="thesis-top"><span>{selectedStock.sector}</span><em className={`signal ${selectedStock.signal.toLowerCase()}`}>{selectedStock.signal}</em></div><h2>{selectedStock.symbol}</h2><p className="company-name">{selectedStock.company}</p><div className="score-ring" style={{"--score":selectedStock.score} as React.CSSProperties}><strong>{selectedStock.score}</strong><small>COMPOSITE<br/>SCORE</small></div><div className="thesis-block"><p>WHY NOW · MODEL INFERENCE</p><span>{selectedStock.rationale}</span></div><div className="thesis-block risk"><p>KEY RISK</p><span>{selectedStock.risk}</span></div><div className="allocation"><span>MODEL ALLOCATION</span><strong>{selectedStock.allocation}%</strong></div><button className="review-button" onClick={()=>setReport({kind:"stock",item:selectedStock})}>OPEN FULL EVIDENCE <span>→</span></button></aside>
      <article className="panel intelligence-panel" id="intelligence"><div className="panel-head"><div><p className="panel-kicker">EVIDENCE INTELLIGENCE</p><h3>Cross-checked events moving the market</h3></div><div className="filter-tabs">{(["ALL","CONFIRMED","DEVELOPING","DISPUTED"] as const).map(f=><button className={eventFilter===f?"active":""} onClick={()=>setEventFilter(f)} key={f}>{f}</button>)}</div></div><div className="verification-rule"><b>CONFIRMED</b> = official primary source or 2+ independent sources. Impact labels are model inference.</div><div className="event-list">{visibleEvents.map(event=><article className="event-item" key={event.id}><div className={`event-impact ${event.impact.toLowerCase()}`}>{event.impact==="POSITIVE"?"↗":event.impact==="NEGATIVE"?"↘":"↔"}</div><div className="event-copy"><div><span>{event.region}</span><i>•</i><span>{timeAgo(event.timestamp,data.generatedAt)}</span><em className={event.status.toLowerCase()}>{event.status}</em></div><h4><button onClick={()=>setReport({kind:"event",item:event})}>{event.title}</button></h4><p>{event.summary}</p><small>Source: {event.source} · {event.sourceCount??1} source(s) · <span>impact is inference</span></small></div><div className="company-tags">{event.companies.map(c=><span key={c}>{c}</span>)}<button onClick={()=>setReport({kind:"event",item:event})}>DOSSIER →</button></div></article>)}</div></article>
      <article className="panel sector-panel"><div className="panel-head"><div><p className="panel-kicker">SECTOR INTELLIGENCE</p><h3>Capital rotation → detailed reports</h3></div><span className="muted">30D SCORE</span></div><div className="sector-list">{data.sectors.map(sector=><button className="sector-row" key={sector.name} onClick={()=>setReport({kind:"sector",item:sector})}><span>{sector.name}</span><i><u style={{width:`${sector.score}%`}}/></i><strong>{sector.score}</strong><em className={sector.change>=0?"positive":"negative"}>{sector.change>=0?"+":""}{sector.change}%</em></button>)}</div><p className="sector-hint">Select a sector for performance horizons, flow quality, revisions, leaders, risks and action.</p></article>
</section>
{data.crypto&&<CryptoSection data={data.crypto} events={data.events}/>}
<footer><span>Research and decision support — not investment advice.</span><span>Every record stores event, publication and observation time.</span></footer></div></section>{newsAlert&&<div className="news-popup-layer" onMouseDown={event=>event.target===event.currentTarget&&dismissNewsAlert()}><aside className={`news-popup ${newsAlert.impact.toLowerCase()}`} role="alertdialog" aria-modal="true" aria-live="assertive"><div className="alert-scan-ring"><i/><i/><i/></div><div className="news-popup-head"><span>● PRIORITY MARKET INTELLIGENCE</span><button onClick={()=>dismissNewsAlert()} aria-label="Dismiss news alert">×</button></div><p>{newsAlert.region} · {newsAlert.status}</p><h3>{newsAlert.title}</h3><small>{newsAlert.source} · {newsAlert.companies.join(" · ")}</small><div><button onClick={()=>{setReport({kind:"event",item:newsAlert});dismissNewsAlert()}}>OPEN EVIDENCE DOSSIER →</button><button onClick={()=>speakText(`${newsAlert.region}. ${newsAlert.title}. Status ${newsAlert.status.toLowerCase()}.`)}>REPLAY VOICE</button><button onClick={()=>dismissNewsAlert()}>DISMISS</button></div></aside></div>}{report&&<EvidenceReport report={report} data={data} onClose={()=>setReport(null)}/>}</main>;
}
